---
- name: copy setup-course dockerfile
  copy:
    src: Dockerfile
    dest: "{{ working_dir }}/{{ docker_setup_course_dockerfile }}"

- name: create the setup course env var file from template
  template:
    src: "env.setup_course.j2"
    dest: "{{ working_dir }}/env.setup_course"

- name: build setup-course microservice image
  docker_image:
    name: illumidesk/setup-course
    build:
      path: "{{ working_dir }}"
      dockerfile: "{{ docker_setup_course_dockerfile }}"
      pull: no
    source: build
    force_source: yes
