---
# Ansible working directory on remote host
working_dir: "{{ ansible_env.PWD }}/illumidesk_deployment"

# End-user account info
org_name: "{{ org_name_param | default('my-org') }}"
course_id: "{{ course_id_param | default('intro101') }}"

## Upstream jupyterhub/jupyterhub and jupyter/docker-stacks hash commits
# https://github.com/jupyter/docker-stacks/commit/e00fd05364dffa4f0547498afe16d9a35f7f0eef
git_nb_hash_commit: "{{ git_nb_hash_commit_param | default('76402a27fd13e649a3166b1da5a162ac476912bf') }}"
# https://github.com/jupyterhub/jupyterhub/commit/65de8c49167738fde9d7e88245593301a2a6a42a
git_jhub_hash_commit: "{{ git_jhub_hash_commit_param | default('3d524f2092c8f1ca4c2953d78156b73107ef8c1c') }}"
# https://github.com/binder-examples/r-conda/commit/f2de174cc427c583d082bfb1d72f10d9c19a5f4e
git_rstudio_hash_commit: "{{ git_rstudio_hash_commit_param | default('f2de174cc427c583d082bfb1d72f10d9c19a5f4e') }}"

# upstream source images
docker_notebook_hash_commit: "{{ git_nb_hash_commit[0:12] }}"
docker_notebook_base_image: "{{ docker_notebook_base_image_param | default('jupyter/datascience-notebook:') }}{{ docker_notebook_hash_commit }}"
docker_jhub_hash_commit: "{{ git_jhub_hash_commit[0:12] }}"
docker_jhub_base_image: "{{ docker_jhub_base_image_param | default('jupyterhub/jupyterhub:1.2') }}"
docker_setup_course_image: "{{ docker_setup_course_image_param | default('illumidesk/setup-course') }}"
docker_rstudio_hash_commit: "{{ git_rstudio_hash_commit[0:12] }}"
docker_rstudio_base_image: "{{ docker_rstudio_base_image_param | default('illumidesk/rstudio:') }}base-{{ docker_rstudio_hash_commit }}"

## Docker
# dockerfiles
docker_jupyterhub_dockerfile: "{{ docker_jupyterhub_dockerfile_param | default('Dockerfile.jhub') }}"
docker_notebook_base_dockerfile: "{{ docker_notebook_base_dockerfile_param | default('Dockerfile.base') }}"
docker_notebook_learner_dockerfile: "{{ docker_notebook_learner_dockerfile_param | default('Dockerfile.learner') }}"
docker_notebook_instructor_dockerfile: "{{ docker_notebook_instructor_dockerfile_param | default('Dockerfile.instructor') }}"
docker_notebook_grader_dockerfile: "{{ docker_notebook_grader_dockerfile_param | default('Dockerfile.grader') }}"
docker_rstudio_dockerfile: "{{ docker_rstudio_dockerfile_dockerfile_param | default('Dockerfile.rstudio') }}"
docker_setup_course_dockerfile: "{{ docker_setup_course_dockerfile_param | default('Dockerfile.setup-course') }}"
docker_theia_dockerfile: "{{ docker_theia_dockerfile_dockerfile_param | default('Dockerfile.theia') }}"
docker_vscode_dockerfile: "{{ docker_vscode_dockerfile_dockerfile_param | default('Dockerfile.vscode') }}"

# built jupyterhub image
docker_illumidesk_jhub_image: "{{ docker_illumidesk_jhub_image_param | default('illumidesk/jupyterhub:') }}{{ docker_jhub_hash_commit }}"

# illumidesk notebooks base and custom images
docker_illumidesk_notebook_base_image: "{{ docker_illumidesk_notebook_base_image_param | default('illumidesk/datascience-notebook:base-') }}{{ docker_notebook_hash_commit }}"
docker_illumidesk_notebook_learner_image: "{{ docker_illumidesk_notebook_learner_image_param | default('illumidesk/notebook:learner') }}-{{ docker_notebook_hash_commit }}"
docker_illumidesk_notebook_grader_image: "{{ docker_illumidesk_notebook_grader_image_param | default('illumidesk/notebook:grader') }}-{{ docker_notebook_hash_commit }}"
docker_illumidesk_notebook_instructor_image: "{{ docker_illumidesk_notebook_instructor_image_param | default('illumidesk/notebook:instructor') }}-{{ docker_notebook_hash_commit }}"

# additional workspace images
docker_illumidesk_rstudio_image: "{{ docker_illumidesk_rstudio_image_param | default('illumidesk/rstudio:base') }}-ild-{{ docker_notebook_hash_commit }}"
docker_illumidesk_theia_image: "{{ docker_illumidesk_theia_image_param | default('illumidesk/theia:base') }}-{{ docker_notebook_hash_commit }}"
docker_illumidesk_vscode_image: "{{ docker_illumidesk_vscode_image_param | default('illumidesk/vscode:base') }}-{{ docker_notebook_hash_commit }}"

# reverse-proxy image
docker_proxy_image: "{{ docker_proxy_image_param | default('jupyterhub/configurable-http-proxy:4.2.0') }}"

## Jupyterhub
## Jupyter Notebook config
jupyter_notebook_config: "{{ jupyter_notebook_config_param | default('jupyter_notebook_config.py') }}"

# Admin users
admin_user: "{{ admin_user_param | default('admin') }}"

# Base URL. Add the / character before the value, for example /acme.
base_url: "{{ base_url_param | default('') }}"

# Mount directories
mnt_root: "{{ mnt_root_param | default('/mnt') }}"

# Mount with AWS EFS
aws_efs_enabled: "{{ aws_efs_enabled_param | default('false') }}"

# Specify the EFS id
efs_id: "{{ efs_id_param | default('') }}"

# Specify the AWS region (used for EFS mounts)
aws_region: "{{ aws_region_param | default('us-west-2') }}"

# Postgres for notebooks labs
postgres_labs_enabled: "{{ postgres_labs_enabled_param | default('false') }}"

# Enable/disable LTI v1.1 config
lti11_enabled: "{{ lti11_enabled_param | default('false')}}"

# LTI 1.1 credentials
lti11_consumer_key: "{{ lti11_consumer_key_result }}"
lti11_shared_secret: "{{ lti11_shared_secret_result }}"

# Enable/disable LTI v1.3 config
lti13_enabled: "{{ lti13_enabled_param | default('false')}}"

# LTI 1.3 config
lti13_client_id: "{{ lti13_client_id_param | default('')}}"
lti13_private_key: "{{ lti13_private_key_param | default('/secrets/keys/rsa_private.pem')}}"
lti13_endpoint: "{{ lti13_endpoint_param | default('https://illumidesk.instructure.com')}}"
lti13_token_url: "{{ lti13_token_url_param | default('https://illumidesk.instructure.com/login/oauth2/token')}}"
lti13_authorize_url: "{{ lti13_authorize_url_param | default('https://illumidesk.instructure.com/api/lti/authorize_redirect')}}"
